- name: Deploying Application (Reddit)
  hosts: app
  tags: deploy-tag
  tasks:
    - name: Get the latest version of app code from GH 
      git:
        repo: 'https://github.com/express42/reddit.git'
        dest: /home/squid/reddit
        version: monolith
      notify: restart puma

    - name: bundle install
      bundler:
        state: present
        chdir: /home/squid/reddit

  handlers:
  - name: restart puma
    become: true
    systemd: name=puma state=restarted
    