--- # --limit [db, app] and/or --tags [db-tag, app-tag]
    # ansible-playbook reddit_app_multiplay.yml --check --limit db --tags db-tag
- name: Configuring MongoDB
  hosts: db
  tags: db-tag
  become: true
  vars:
    mongo_bind_ip: 0.0.0.0
  tasks:
    - name: Changing mongo config file
      template:
        src: ./templates/mongod.conf.j2
        dest: /etc/mongod.conf
        mode: 0644
      notify: restart mongod

  handlers:
  - name: restart mongod
    service: name=mongod state=restarted

- name: Configuring Application
  hosts: app
  tags: app-tag
  become: true
  vars:
   db_host: 10.132.0.44
  tasks:
    - name: Add unit file for Puma
      copy:
        src: ./files/puma.service
        dest: /etc/systemd/system/puma.service
      notify: reload puma

    - name: Add config for DB connection
      template:
        src: ./templates/db_config.j2
        dest: /home/squid/db_config
        owner: squid
        group: squid

    - name: enable puma
      systemd: name=puma enabled=yes

  handlers:
  - name: reload puma
    systemd: name=puma state=restarted

- name: Deploying Application (Reddit)
  hosts: app
  tags: deploy-tag
  tasks:
    - name: Get the latest version of app code from GH 
      git:
        repo: 'https://github.com/express42/reddit.git'
        dest: /home/squid/reddit
        version: monolith
      notify: restart puma

    - name: bundle install
      bundler:
        state: present
        chdir: /home/squid/reddit

  handlers:
  - name: restart puma
    become: true
    systemd: name=puma state=restarted
