--- # --tags [db-tag, app-tag]
    # ansible-playbook reddit_app_multiplay.yml --check --tags db-tag
- name: Configure hosts and deploy app
  hosts: all
  vars:
    mongo_bind_ip: 0.0.0.0 
    db_host: 10.132.0.31

  tasks:    
    - name: Config for mongo
      become: true
      template:
        src: ./templates/mongod.conf.j2
        dest: /etc/mongod.conf
        mode: 0664
      tags: db-tag
      notify: restart mongod     
  
    - name: Copy init file for puma    
      become: true
      copy:
        src: ./files/puma.service
        dest: /etc/systemd/system/puma.service
      tags: app-tag
      notify: reload puma

    - name: Add config for DB connection
      template:
        src: ./templates/db_config.j2
        dest: /home/squid/db_config
      tags: app-tag

    - name: Enable puma service
      become: true
      systemd: name=puma enabled=yes
      tags: app-tag
    
    - name: Get the latest version of application code
      git:
        repo: https://github.com/express42/reddit.git
        dest: /home/squid/reddit
        version: monolith
      tags: deploy-tag
      notify: reload puma
    
    - name: Bundler install
      bundler:
        state: present
        chdir: /home/squid/reddit
      tags: deploy-tag


  handlers:
    - name: restart mongod
      become: true
      service: name=mongod state=restarted

    - name: reload puma
      become: true
      systemd: name=puma state=restarted
