---
# tasks file for app
- name: Show information about "env" of this host
  debug:
    msg: "This host is in {{ env }} environment!"

# - pause:

- name: Add unit file for Puma
  copy:
    src: puma.service
    dest: /etc/systemd/system/puma.service
  notify: restart puma

- name: Add config for DB connection
  template:
    src: db_config.j2
    dest: /home/squid/db_config
    owner: squid
    group: squid

- name: enable puma
  systemd:
    name: puma
    enabled: yes

# - name: Deploying Application (Reddit)
#   hosts: app
#   tags: deploy-tag
#   tasks:
#     - name: Get the latest version of app code from GH 
#       git:
#         repo: 'https://github.com/express42/reddit.git'
#         dest: /home/squid/reddit
#         version: monolith
#       notify: restart puma

# - name: bundler install
#   bundler:
#     state: present
#     chdir: /home/squid/reddit
